language: rust
rust:
  - nightly
before_script:
  - rustup component add clippy
script:
  - cd server
  - cargo build
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test --verbose